name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu:20.04
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - run: apt-get install -y node
      - run: curl -L https://github.com/danramteke/leaf-press/releases/download/0.4.22/leaf-press-ubuntu-20.04.tgz | tar xzf -
      - run: ./leaf-press build
      - run: yarn build
      - 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          cname: hananddan.com